# This is an R shiny application that will call an openmp  
#   program and generate data, and then display that data 

library(shiny)
library(ggplot2)

# read data
#DATA <- read.csv(file="data.csv", header=FALSE, sep=",")

generatePlot <- function(num){
    # returns a ggplot generated by running an openmp executable
    system(sprintf("./openMP %d",num))
    DATA <- read.csv(file="data.csv", header=FALSE, sep=",")
    mat <- as.matrix(DATA)
    plot <- ggplot()+geom_point(aes(x=mat[1,],y=mat[2,]))
    plot
}

ui <- fluidPage(
    titlePanel("OPENMP AND R SHINY"),
    sidebarLayout(
        sidebarPanel(
            numericInput("num","NUMBER:",5,min=1,max=100, step=1),
            actionButton("generate","GENERATE DATA")
        ),
        mainPanel(
            plotOutput("mainPlot")
        )
    )
)

# The server is simple, simply generate a new plot when the user selects 'GENERATE DATA'
#   Note that isolate is used so that the graph isn't regenerated when input$num changes
server <- function(input,output,session){
    output$mainPlot <- renderPlot({
        input$generate
        mainPlot <- isolate(generatePlot(input$num))
        mainPlot
    })
}

# Run the application
shinyApp(ui = ui, server = server)
